root = "../.."
tmp_dir = "session-service/output"

[build]
cmd = "go build -gcflags \"all=-N -l\" -o ../output/main.exe ."
entrypoint = "session-service/output/main.exe"
include_dir = ["session-service/src", "backend-lib/src"]

[log]
time = true
