version: "3"

tasks:
  start-registration-server:
    desc: Start the registration server
    dir: registration-server/src
    cmds:
      - air

  start-authentication-server:
    desc: Start the authentication server
    dir: authentication-server/src
    cmds:
      - air
