POST http://localhost:3004/inventory/add
Content-Type: application/json
X-Session-Id: <session-id-from-create>

{
  "characterId": "<character-id-from-create>",
  "templateId": "<template-id-from-content-service>",
  "quantity": 1
}
