POST http://localhost:3004/create
Content-Type: application/json
X-Session-Id: hZt3T1nDY3bR0LkC567l3SXPJZS-i4th18CJqvC9quI

{
  "name": "Thrall",
  "race": "orc",
  "class": "shaman",
  "gender": "male",
  "appearance": {
    "skinColor": 0,
    "faceId": 0,
    "hairStyleId": 0,
    "hairColor": 0,
    "facialHairId": 0
  }
}
